mcdope/pam_usb

debian/config, debian/copyright, debian/libpam-usb.postinst, debian/libpam-usb.postrm, debian/templates, tools/pamusb-conf
This introduces a working configuration right after installing the package.
=> [Debian] Packaging: working config out of the box

src/conf.c, src/pad.c, src/pamusb-check.c, src/xpath.c
Closes https://github.com/mcdope/pam_usb/security/code-scanning/3?query=ref%3Arefs%2Fheads%2Fmaster
Closes https://github.com/mcdope/pam_usb/security/code-scanning/2?query=ref%3Arefs%2Fheads%2Fmaster
Closes https://github.com/mcdope/pam_usb/security/code-scanning/4?query=ref%3Arefs%2Fheads%2Fmaster
Closes https://github.com/mcdope/pam_usb/security/code-scanning/1?query=ref%3Arefs%2Fheads%2Fmaster
=> Fix code scanning alerts

debian/control
- added missing package to depends
- also added some other packages previously assumed to be there / pulled in by other packages
closes issue #23
=> Fix Issue #23: missing requirement

ChangeLog, debian/changelog, src/version.h
This increases the version to 0.7.1 and updates the changelogs
=> Version bump to 0.7.1, changelog update

debian/changelog
Update debian/changelog in preparation for git tag / deb build
=> Prepare 0.7.2

debian/control
=> #63: Add missing depends required for debconf stuff

doc/pamusb-check.1, src/pamusb-check.c, tools/pamusb-conf
=> #70: Add --version to pamusb-check, add version info to usage info in pamusb-conf

ChangeLog, debian/changelog, debian/control, debian/libpam-usb.NEWS
* Updates changelogs
* Updates debian news
* Bump version
=> #67: Bump version, prepare release

src/local.c
Improve compatibility with PolicyKit in graphical environments
=> #75: Improve PolicyKit compatibility

src/tmux.c
=> #79: Prepend target-session parameter with dollar sign

src/pamusb-check.c, src/version.h
=> #86: Fix PUSB_VERSION and use it in pamusb-check, too

.gitignore, src/local.c, src/local.h
Reworks "get tty by Xorg" into something supporting Wayland, too.
Closes #81
=> #81: Add compatibility with Wayland

AUTHORS, ChangeLog, Makefile, debian/changelog, src/version.h
=> #85: Prepare 0.8.1 release

.github/workflows/nightly-build-on-own-server.yml, Makefile
- adds `sourcegz` make target
- adds Github workflow to build and upload nightly builds
- use `sourcegz` target to build gz for `make zst`
Closes #134
=> [WIP] #134: Automatic regular releases 

Makefile
=> #132: Fix pam-auth-update config being installed on systems not supporting it

doc/pamusb-agent.1, doc/pamusb-check.1, doc/pamusb-conf.1
=> #155 update manpage agent

.github/workflows/build-and-test-on-own-server.yml
=> #159: Add lockfile to tests action

Makefile, doc/QUICKSTART, doc/SECURITY, doc/TROUBLESHOOTING, fedora/SPECS/pam_usb.spec
=> #139 add make target to update docs

src/local.c, src/tmux.c
=> #175: Fix tmux in tmux circumventing local check

AUTHORS, ChangeLog, README.md, arch_linux/PKGBUILD_stable, debian/changelog, debian/config, debian/source/options, doc/CONFIGURATION, doc/QUICKSTART, doc/SECURITY, doc/TROUBLESHOOTING, doc/pam_usb.conf, fedora/SPECS/pam_usb.spec, src/local.c, src/version.h, tools/pamusb-conf
=> Prepare 0.8.3

src/local.c
- improves tty detection by loginctl
- adds remoteness detection by loginctl
Closes #196
=> #196: Improve loginctl handling

src/local.c, src/process.c, src/tmux.c
- force external commands to english locale
- some string/mem fixes
- fix `pusb_get_process_envvar()` returning local variable
Maybe affected/fixed issues by this: #205, #199 - but needs testing/validation
=> Fix misc. problems 

.github/workflows/build-and-test-on-own-server.yml, .github/workflows/nightly-build-on-own-server.yml, .github/workflows/package-with-docker-on-own-server.yml
=> #234: [Actions] Ensure cleanup steps are executed

Dockerfile.fedora, fedora/SPECS/pam_usb.spec
=> #253: Dont require rsync just for packaging

.github/workflows/build-and-test-on-own-server.yml, .github/workflows/nightly-build-on-own-server.yml, .github/workflows/package-with-docker-on-own-server.yml, src/volume.c, tests/can-actually-be-used/mount-image.sh
Fixes an issue with piped commands in the test scripts (and uses a new secret)
=> CI: Fix image handling
