- src/pad.c
- tests/can-actually-be-used/run-tests.sh
- tests/can-actually-be-used/setup-dummyhcd.sh
- tests/can-actually-be-used/test-conf-doesnt-add-user-twice.sh
- tools/pamusb-conf
This change introduces a check if the user to be added is already configured, if so: exit with error
Closes #28
> #28: make sure only one device per user can be added

- debian/config
The previously used regex to find available devices wasn't properly capturing nvm device name patterns. 
This is now fixed. Closes #29
> #29: Fix NVMe storage handling

- debian/config
Somewhere between the versions used by focal and groovy the output of `udisksctl` was changed. Previously it listed volumes array-like, clearly distinguishable. This is now changed to a one-per-line listing, without dividers except the newline. 
Since this only applies to newer versions of `udisksctl` and I don't want to write a grep regex handling both cases this PR changes the detection to use `ls -l /dev/$DEVICE`.
Also adds some more (disabled) debug output
Closes #26
> #26: Fix volume detection on later versions of udisksctl

- debian/control
This fixes another missing dependency, for Debian minimal (truely, without Desktop)
Closes #23 (again)
> #23: Add python3-gi to debian package requirements

- Makefile
- debian/changelog
- debian/copyright
This sets distribution field in changes file to "unstable", so Lintian doesn't report bad-distribution-in-changes-file anymore.
Closes #38 
Closes #42
> #38: Fix Lintian error 'bad-distribution-in-changes-file'

- Makefile
Current libpam versions only look in the arch-native lib directory for modules. 
Till now we always targeted /usr/lib, even on x64. This is now fixed.
Closes #36
> #36: Use correct target lib dir on x64 machines

- ChangeLog
- Makefile
- debian/changelog
- debian/copyright
- doc/CONFIGURATION
- doc/pam_usb.conf
- src/conf.c
- src/conf.h
- src/local.c
- src/process.c
- src/process.h
This reworks `deny_remote` handling to use process based checking. 
Instead of checking utmp and hoping there is an entry for the current session, which there often isn't for virtual terminals, we now check the chain of parent processes. If any parent process is sshd or telnetd we deny authentication.
This renders `unknown_pts_as_local` obsolete - removed.
Closes #8 (again)
See #39
> #8/#39: Rework deny_remote / remove unknown_pts_as_local

- tools/pamusb-agent
During suspend and resume it is possible to have usb disconnect and
connect events that would lock the system immediately. This patch
prevents that. After resuming from suspend removal events will be
blocked for 5 seconds. If the usb key is still present after resume the
session will be unlocked.
> Fix: don't lock after resume.

- src/pad.c
So far sync() was used to flush updated pads. When you have heavy file IO running in parallel this is likely to never complete until the IO is finished.
This should be fixed by this PR.
> #57: Fix file syncing

- arch_linux/PKGBUILD
- doc/pamusb-check.1
I wanted to try to get this on my Arch desktop, and was having troubles. No clue why I checked, but the PKGBUILD was using a different fork. This will allow anyone deciding to use this to PKGBUILD in this repo to pull the right repo.
> Correct PKGBUILD to use correct repo

- .github/workflows/build-and-test-on-own-server.yml
This adds two new steps to the job to setup `user.name` and `user.mail` for `git`. For this a new secret, $TEST_RUNNER_MAIL, is introduced.
> #74: Fix "Build & test on own server"

- src/local.c
Some enviroments, for example XFCE, set DISPLAY to a value including the screen identifier. This is causing the utmp check to fail since the session is registered using only the display part. 
This fixes this by cutting the screen identifier from the read env var.
> #72: Fix screen part in DISPLAY env var causing utmp check to fail

- tools/pamusb-agent
Previously, the splitting of cmd argument causes some limitations on complex commands
I've modified this to take the cmd argument as is, which allows Executing Commands containing:
- pipes | 
- redirect operator > 
- backticks ``
- dollar signs $
...
I've tested it with this complex command to lock the screen on systemd supported OS:
```xml
<cmd>loginctl lock-session `loginctl list-sessions | grep tty2 |  tr -s ' ' | cut -d' ' -f2`</cmd>
```
> Allow Executing Complex Commands in pamusb-agent

- src/local.c
[ly](https://github.com/nullgemm/ly) is a terminal-based login manager/display manager, so white-listing it as local.
Tested and worked on my machine, however at the 2nd login time, it gives an error:
```
(process:12375): GLib-GObject-WARNING **: 10:00:21.026: cannot register existing type 'UDisksClient'
(process:12375): GLib-GObject-CRITICAL **: 10:00:21.028: g_type_add_interface_static: assertion 'G_TYPE_IS_INSTANTIATABLE (instance_type)' failed
(process:12375): GLib-GObject-CRITICAL **: 10:00:21.028: g_type_add_interface_static: assertion 'G_TYPE_IS_INSTANTIATABLE (instance_type)' failed
(process:12375): GLib-CRITICAL **: 10:00:21.028: g_once_init_leave: assertion 'result != 0' failed
(process:12375): GLib-GIO-CRITICAL **: 10:00:21.028: g_initable_new_valist: assertion …
```
> Identify ly as local login.

- src/local.c
The MR is incomplete and fixes just the login part, reverting for proper fix.
Reverts mcdope/pam_usb#103
> Revert "Identify ly as local login."

- src/local.c
Currently, using loginctl to obtain the tty results in a segmentation fault because the second argument to `stat` should be a pointer (https://linux.die.net/man/2/stat).
Didn't come up as a compilation error because `<sys/stat.h>` wasn't being included, so I added that as well.
> Fix type for argument to stat

- src/local.c
This workarounds the problem from #115 by whitelisting tty logins as local
Closes #115
> #115: Whitelist 'login' as local service

- src/local.c
#110 wouldn't require `DISPLAY` being set if the agent would be excluded from the local check. Since agent calls will for sure always be local we can just whitelist it so DISPLAY isn't required in the first place.
Fixes #110
> #110: Whitelist pamusb-agent for local check

- .github/workflows/can-be-built-successfully.yml
- .github/workflows/package-with-docker-on-own-server.yml
- Dockerfile.arch
- Makefile
- arch_linux/PKGBUILD
- Adds docker based build environment for Arch
- Adds make zst target
- Adds make target for docker based arch build
- Updates PKGBUILD
- Change arch versioning to $version.$countOfCommitsOnTop
Guess this could break using the PKGBUILD file for AUR since it now refers to a local tgz created by the make target. Feel free to fork if needed but I also left the git part in, just comment one line and uncomment another...
> [Packaging] [Arch] Add docker based builds

- src/local.c
This fixes obtaining the session tty from the display server for systems using a slightly different invocation syntax for `Xorg`
Closes #140
> #140: local.c: Fix 'tty from displayserver'

- tools/pamusb-conf
This add an option to remove the pad files, for use in case there are pad verification errors you want to resolve.
This also corrects the outdated version stated in `pamusb-conf`
> [pamusb-conf] Add --reset-pads=<username> option to, well..., reset the pads

- Makefile
> #132: Fix deb package not containing pam-auth-update config anymore

- src/local.c
> #181: Whitelist 'kde'/klockscreen

- src/local.c
> #189: Whitelist lxdm and xscreensaver for local check

- src/local.c
> #188: Fix stupid bug while shortening DISPLAY with screen identifier

- doc/pam_usb.conf
- src/local.c
This replaces the hardcoded whitelist in `local.c` with a config based one
Closes #184
> #184: Refactor whitelist

- .github/workflows/build-and-test-on-own-server.yml
- .github/workflows/devskim.yml
- .github/workflows/nightly-build-on-own-server.yml
- .github/workflows/package-with-docker-on-own-server.yml
Moves CI to homelab host (and adds port support)
> Move CI to homelab

- .github/workflows/nightly-build-on-own-server.yml
- src/local.c
This reworks the utmp check to not check every element. 
Some display managers rely on the legacy property ut_addr, which is mapped to ut_addr_v6[0]. 
If they use ut_addr and just set it to zero the other fields are kinda "undefined" / not necessary 0
> #204: Rework utmp check

- ChangeLog
- arch_linux/PKGBUILD_git
- arch_linux/PKGBUILD_stable
- debian/changelog
- fedora/SPECS/pam_usb.spec
- src/version.h
- tools/pamusb-conf
> Prepare 0.8.4

- src/local.c
This adds a check for XRDP_SESSION being set, if yes and deny_local is active: deny
See #202
> Enhancement: Deny local check if XRDP_SESSION is set

- src/pad.c
> Enhancement: deny if pads can't be updated (i.e RO media)

- src/conf.c
- src/device.c
- src/local.c
- src/pad.c
- src/pam.c
- src/process.c
- src/process.h
- src/tmux.c
- src/volume.c
Implement some suggested changes by DeepSeek Coder v2
> Enhancement: Fix issues identified by deepseek-coder-v2

- fedora/SPECS/pam_usb.spec
Signed-off-by: YiLin.Li <YiLin.Li@linux.alibaba.com>
> fedora/SPECS/pam_usb.spec: add BuildRequires

- Makefile
- doc/pamusb-pinentry.1
- fedora/SPECS/pam_usb.spec
> #255: Create pamusb-pinentry.1

- src/local.c
In the VSCode Microsft distributed version you can run it "remotely". Like you start the IDE as a server-only at one PC and access it through Microsoft servers and its authentication on another PC, and inside the IDE you can access an integrated terminal that is running in the remote PC. And when I was using sudo for some commands the pam_usb checked for my puggled device and authorized it.
This is caused by VSCode not registering it's sesssion(s) in utmp.
Reference here: https://code.visualstudio.com/docs/remote/tunnels
> add check for VSCode remote tunnel
